# Generated by Django 3.1.7 on 2021-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='p_fake',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='p_real',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
