# Generated by Django 3.1.7 on 2021-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210327_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='binary_mask',
            field=models.ImageField(null=True, upload_to='binary_masks/'),
        ),
    ]
