# Generated by Django 3.1.7 on 2021-05-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210327_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvotes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
