# Generated by Django 3.1.7 on 2021-05-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_auto_20210515_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvoted_posts', models.ManyToManyField(related_name='downvoted_posts', to='mainapp.Post')),
                ('upvoted_posts', models.ManyToManyField(related_name='upvoted_posts', to='mainapp.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
